### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by shuiyao-sg** [AY1920S1-CS2103T-F11-4/main#26]
* Jeremy Tan Jierui: Lecture notes feature
    - [x] v1.2: Note class, functioning similarly to the Person class, but without images
    - [x] v1.3: support image uploads

* Irene Lee Li Ying Irene: statistics feature
    - [x] v1.2: support "stats", "questions" commands
    - [x] v1.3: support "report", "overview" commands

* Shui Yao: revision task and notification feature
    - [x] v1.2: support "add", "delete", "done", "clear" commands.
    - [x] mid-v1.3: implement testing for commands in v1.2. support task for questions, support "overdue".
    - [x] v1.3: support "rlist", "finished", "unfinished" features. Support push notification.

* Wang Xueting: question feature
    - [x] v1.2: support "addq", "listq", "deleteq", commands
    - [x] v1.3: support "editq", "findq", filter by difficulty, filter by subject, clearq features

* Zhang Dongjun: test mode feature
    - [x] v1.2: quiz mode interface, support question running through
    - [x] v1.3: Modify Ui to support the quiz mode

**Comment by Parcly-Taxel** [comment]
```
- [ ] thing A
- [ ] thing B
```

produces
- [ ] thing A
- [ ] thing B
